server:
  port: 5555

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,env,refresh,routes

## Mapping routes manually
#zuul:
##  ignored-services: 'organization-service' # exclude the Eureka service ID organization-service from the automated mappings done by Zuul.
#  ignored-services: '*' # exclude the registration of all eureka service ID based routes.
#  prefix: /api  # All defined services will be prefixed with /api
#  routes:
#    organization-service: /organization/**
#    licensing-service: /licensing/**

## Manual mapping of routes using static urls
#zuul:
#  prefix: /api
#  routes:
#    license-static:
#      path: /license-static/**
#      url: http://license-static:8085

## Manual mapping of routes using static urls, mapping license static service statically to multiple routes
#zuul:
##  ignored-services: '*'
#  prefix: /api
#  routes:
#    license-static:
#      path: /license-static/**
#      serviceId: license-static
#
#ribbon:
#  eureka:
#    enabled: true
#
#license-static:
#  ribbon:
#    listOfServers: http://license-static:8085, http://license-static:8086, http://license-static:8087
