example.property: "I AM IN THE DEFAULT"
spring.h2.console.enabled: "true"
spring.jpa.hibernate.ddl-auto: "none"
spring.datasource.initialization-mode: "always"
spring.jpa.show-sql: "true"
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
redis.server: "redis"
redis.port: "6379"
signing.key: "345345fsdfsf5345"