version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_prod"
      POSTGRES_PASSWORD: "p0stgr@s_prod"
      POSTGRES_DB: "eagle_eye_prod"
  config-service:
    extends:
      file: ../common/docker-compose.yml
      service: config-service
  licensing-service:
    extends:
      file: ../common/docker-compose.yml
      service: licensing-service
    environment:
      PROFILE: "prod"
