#server:
#  port: 8888
#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/azimbabu/config-repository
#          search-paths: licensing-service, organization-service


####
#Classpath or file-based solution
####
server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config/licensing-service,classpath:/config/organization-service,classpath:/config/zuul-service