version: '2'
services:
  database:
    image: postgres:12.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB: "eagle_eye_local"
  config-service:
    image: azimbabu/config-service:chapter3
    ports:
      - "8888:8888"
  licensing-service:
    image: azimbabu/licensing-service:chapter3
    ports:
      - "8080:8080"
    environment:
      PROFILE: "local"
      CONFIGSERVER_URI: "http://config-service:8888"
      CONFIGSERVER_PORT: "8888"
      DATABASESERVER_PORT: "5432"